name: CI/CD

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TIMESTAMP=$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Set up Node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm
      - name: Build client
        working-directory: ./client
        run: |
          npm ci
          npm run build
          mv build ../public_html
          npm test
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build API
        run: ./gradlew build --console plain --refresh-dependencies --rerun-tasks
      - name: Bundle for Beanstalk
        # run this on every branch, even though only master will deploy it
        # files have a .yaml extension for easier editing, but EB needs .config
        run: |
          for f in .ebextensions/*.yaml; do mv $f $f.config; done
          zip build/eb_bundle.zip -r public_html
          zip build/eb_bundle.zip -r .ebextensions
          zip build/eb_bundle.zip -j build/libs/cookbook-*.jar
          zip build/eb_bundle.zip Procfile
      - name: Deploy Beanstalk
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: einaregilsson/beanstalk-deploy@v17
        with:
          aws_access_key: AKIAYLRQLC7OXCOKSHPK
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: cookbook
          environment_name: Cookbook-env
          version_label: ${{ format('github-{0}-{1}-{2}', github.run_number, env.TIMESTAMP, github.sha) }}
          region: us-west-2
          deployment_package: build/eb_bundle.zip
          wait_for_deployment: false

